#Postgres and JPA Configure
spring.application.name=message-generator
spring.datasource.url=jdbc:postgresql://localhost:5432/db_aula
spring.datasource.username=postgres
spring.datasource.password=22091992
spring.datasource.driver-name=org.postgresql.Driver

#JPA
spring.jpa.properties.temp.use_jdbc_metadata_defaults = false
spring.jpa.database-plataform=org.hibernate.dialect.PostgresSQL9Dialect

